resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta:  "reference/HES45.fna"
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  mappability: "reference/access-5k-mappable.hg19.bed"

cnvkit_create_targets:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_create_anti_targets:
  container: "docker://gmsuppsala/somatic:develop"

cnvkit_build_normal_reference:
  container: "docker://gmsuppsala/somatic:develop"
